name: p_project
description: A Base Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: ^3.0.9
  dio_flutter_transformer: ^3.0.2
  # rxdart: ^0.22.6
  provider: ^4.0.4
  permission_handler: ^4.0.0
  image_crop: ^0.3.2
  image: ^2.1.11
  filesize: ^1.0.4
  photo_view: ^0.9.1
  event_bus: ^1.1.0
  pull_to_refresh: ^1.5.8

  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  moor: ^2.4.2

  # flutter.dev
  image_picker: ^0.6.2+3
  share: ^0.6.3+5
  statsfl: ^1.0.0+2

  # animation
  simple_animations: ^1.3.7

  p_umeng: ^0.0.3

  # p_params:
  #   path: ../p_params
  # p_install:
  #   path: ../flutterplugin/p_install

  router:
    path: ../flutter_lib/router
  screen_adaptation:
    path: ../flutter_lib/screen_adaptation
  p_image_loader:
    path: ../flutter_lib/p_image_loader
  p_widget:
    path: ../flutter_lib/p_widget
  p_utils:
    path: ../flutter_lib/p_utils
  p_img_compress:
    path: ../flutter_lib/p_img_compress
  p_base:
    path: ../flutter_lib/p_base

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.0
  # flutter_test:
  # sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/main/
    - assets/common/
    - assets/sticker/
