name: p_project
description: A Base Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  dio_flutter_transformer: ^3.0.2
  provider: ^4.3.2+2
  permission_handler: ^5.0.1+1
  image_crop: ^0.3.4
  image: ^2.1.18
  filesize: ^1.0.4
  photo_view: ^0.10.2
  event_bus: ^1.1.1
  pull_to_refresh: ^1.6.2

  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  # moor: ^2.4.2

  # flutter.dev
  image_picker: ^0.6.7+12
  share: ^0.6.5+4

  # animation
  simple_animations: ^2.2.3

  p_umeng: ^0.0.3

  # p_params:
  #   path: ../p_params
  # p_install:
  #   path: ../flutterplugin/p_install

  router:
    path: ../flutter_lib/router
  screen_adaptation:
    path: ../flutter_lib/screen_adaptation
  p_image_loader:
    path: ../flutter_lib/p_image_loader
  p_widget:
    path: ../flutter_lib/p_widget
  p_utils:
    path: ../flutter_lib/p_utils
  p_img_compress:
    path: ../flutter_lib/p_img_compress
  p_base:
    path: ../flutter_lib/p_base

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  hive_generator: ^0.8.1
  build_runner: ^1.10.3

flutter:
  uses-material-design: true
  assets:
    - assets/main/
    - assets/common/
    - assets/sticker/
