name: p_project
description: A Base Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^3.0.7
  dio_flutter_transformer: ^3.0.2
  fluttertoast: ^3.1.3
  rxdart: ^0.22.6
  flutter_screenutil: ^0.7.0
  provider: ^4.0.4
  permission_handler: ^4.0.0
  flutter_spinkit: ^4.1.1+1
  launch_review: ^2.0.0
  image_crop: ^0.3.2
  image: ^2.1.11
  filesize: ^1.0.4
  flutter_luban: ^0.1.11
  photo_view: ^0.9.1
  devicelocale: ^0.2.0
  event_bus: ^1.1.0
  pull_to_refresh: ^1.5.7

  # flutter.dev
  device_info: ^0.4.1+4
  shared_preferences: ^0.5.6
  cached_network_image: ^2.0.0-rc
  package_info: ^0.4.0+13
  url_launcher: ^5.4.1
  path_provider: ^1.5.1
  image_picker: ^0.6.2+3
  # webview_flutter: ^0.3.18+1
  # google_maps_flutter: ^0.5.22+3
  share: ^0.6.3+5
  # video_player: ^0.10.7 #选取视频

  # animation
  simple_animations: ^1.3.7

  p_params:
    path: ../p_params
  p_install:
    path: ../flutterplugin/p_install

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  # flutter_test:
  # sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/main/
    - assets/images/common/
